[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
]
build-backend = "hatchling.build"

[project]
name = "stripepy"
description = "A stripe recognition tool developed by Paulsen Group @University of Oslo"
dynamic = ["version"]
authors = [
    {name="Andrea Raffo", email="andrea.raffo@ibv.uio.no"},
    {name="Bendik Berg", email="bendber@ifi.uio.no"},
]
maintainers = [
    {name="Roberto Rossini", email="roberto.rossini@ibv.uio.no"},
    {name="Andrea Raffo", email="andrea.raffo@ibv.uio.no"},
]
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",

    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",

    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
keywords = [
    "hi-c",
    "hic",
    "stripe",
    "stripes",
    "architectural stripe",
    "contact map",
    "cooler",
    "stripe recognition",
]

requires-pyhton = ">=3.9"
dependencies = [
    "bioframe >0.7, <1",
    "h5py >3, <4",
    "hictkpy[scipy] >=1, <2",
    "matplotlib >=3.8, <4",
    "numpy >=1.26, <2",
    "pandas >=2.0, <3",
    "scikit-learn >=1.5, <2",
    "scipy >=1.10, <2",
    "seaborn >=0.13, <1"
]

[project.optional-dependencies]

test = [
    "pytest",
    "stripepy",
]

dev = [
    "stripepy[test]",
    "black",
    "isort",
    "pre-commit",
]

[project.scripts]
stripepy = "stripepy:main"

[project.urls]
Homepage = "https://github.com/paulsengroup/StripePy"
Issues = "https://github.com/paulsengroup/StripePy/issues"
Repository = "https://github.com/paulsengroup/StripePy.git"
Source = "https://github.com/paulsengroup/StripePy"

[tool.hatch.version]
source = "vcs"
fallback-version = "unknown"

[tool.hatch.build.targets.wheel]
packages = ["src/stripepy"]

[[tool.hatch.envs.test.matrix]]
python = ["3.9", "3.10", "3.11", "3.12", "3.13"]
