[build-system]
requires = ["hatchling"]?
build-backend = "hatchling.build"?

[project]
name = "stripepy_obikenobi23"?
version = ""?
dynamic = ["version"]
authors = [?
    {name="Roberto Rossini", email=""},
    {name="Andrea Raffo", email=""},
    {name="Bendik Berg", email=""},
]
maintainers = [?
    {name="", email="},
]
description = "A stripe recognition tool developed by Paulsen Group @University of Oslo"?
readme = "README.md"
requires-pyhton = ">=3.0"?
dependencies = [
    "bioframe >0.7, <1",
    "h5py >3, <4",
    "hictkpy >=0.0.5, <1",
    "matplotlib >=3.8, <4",
    "numpy >=1.26, <2",
    "pandas >=2.0, <3",
    "scikit-learn >=1.5, <2",
    "scipy >=1.10, <2",
    "seaborn >=0.13, <1"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: ",?
    "Operating System :: OS Independent",
]
keywords = []

[project.urls]
Source = ""?
Issues = ""?

[project.scripts]
